/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stdint.h"

#define RCC_Base 0x40021000
#define GPIOA_Base 0x40010800

#define APB2ENR    *((volatile uint32_t *)(RCC_Base +0x18))
#define CRH        *(volatile uint32_t *)(GPIOA_Base + 0x04)
#define ODR        *(volatile uint32_t *)(GPIOA_Base + 0x0C)

typedef volatile unsigned int vint32_t;


typedef union{
	vint32_t All_Ports;
	struct{
		vint32_t Reserved : 13;
		vint32_t PIN13 : 1 ;
	}pin;

}R_ODR_u;


volatile R_ODR_u* RE = (volatile R_ODR_u* )(GPIOA_Base + 0x0C);
int main(void)
{

	int i = 0;
	APB2ENR |= (1<<2);
	CRH = 0xff0fffff;
	CRH |= 0x00200000;
  while(1){
	  //ODR |=(1<<13);
	  RE->pin.PIN13 = 1;
	  for(i = 0;i<90000;i++);
	  RE->pin.PIN13 = 0;
	  //ODR &= ~(1<<13);
	  for(i = 0;i<90000;i++);
  }
return 0;
}
