/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include"stdint.h"
#define RCC_Base 0x40021000
#define GPIOA_Base 0x40010800

#define APB2ENR    *((volatile uint32_t *)(RCC_Base +0x18))
#define CRH        *(volatile uint32_t *)(GPIOA_Base + 0x04)
#define ODR        *(volatile uint32_t *)(GPIOA_Base + 0x0C)

#define RCC_CFGR    *((volatile uint32_t *)(RCC_Base +0x04))
#define RCC_CR    *((volatile uint32_t *)(RCC_Base +0x0))

typedef volatile unsigned int vint32_t;





int main(void)
{
int i =0;
    APB2ENR |= 1<<2;
	CRH = 0xff0fffff;
	CRH |= 0x00200000;
	RCC_CFGR |= (0b0110 << 18);
	RCC_CFGR |= (0b101 << 11);
	RCC_CFGR |= (0b100 << 8);
	RCC_CFGR |= (0b10 << 0);
	RCC_CR |= 1<<24;
  while(1){
	  ODR |=(1<<13);

	  for(i = 0;i<5000;i++);
	  ODR &= ~(1<<13);
	  for(i = 0;i<5000;i++);
  }
return 0;
}
